name: Readme CI
on:
  push:
    branches: [main]
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  release:
    name: Update README
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Update note summary
        uses: AnandChowdhary/notes-summary@master
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"